{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "charts2.serviceAccountName" . }}
  labels:
{{ include "charts2.labels" . | indent 4 }}
{{- end -}}
